### ISSUE TITLE
package count off

### ISSUE THREAD

**Issue by lnussel** [openSUSE/build-check-statistics#1]
the package counter for openSUSE:Factory-x86_64-standard says 12225 packages, but there are only 10089 source containers in Factory of which 7805 are actually listed in the table

**Comment by kraih** [comment]
It currently shows the number of all packages in the repo, with and without errors/warnings. Guess we could change it show only the number of packages with errors/warnings.

**Comment by DimStar77** [comment]
> osc ls openSUSE:Factory | wc -l
10089

That's irrespective of errors or not - but there are simply not more there

**Comment by kraih** [comment]
@DimStar77 I get the build results from https://build.opensuse.org/public/build/openSUSE:Factory/standard/x86_64/_jobhistory?code=lastfailures, which gives me 12226 packages (after removing duplicates).

**Comment by coolo** [comment]
I'm afraid this includes meanwhile dropped packages

**Comment by kraih** [comment]
@coolo That's too bad. But during the update process i also fetch https://build.opensuse.org/public/build/openSUSE:Factory/_result, is that package list more up to date? Then i could just ignore build results for packages that don't appear in both lists.

**Comment by kraih** [comment]
I've changed what packages are displayed for now (https://github.com/openSUSE/build-check-statistics/commit/7c699cc2ff025abc6aba8f57df8f008ca5587e0c), but will put filtering out dropped packages on the todo list.

**Comment by coolo** [comment]
_result should have everything the scheduler knows about. This might be outdated too, but only by means of minutes not years ;)

**Comment by kraih** [comment]
Considering that the database will only get updated once a day, and that it currently takes about one hour and forty minutes, being a few minutes outdated seems perfectly acceptable. 😉

**Comment by kraih** [comment]
This should be fixed now.
