### ISSUE TITLE
Invalid HTTP when opening package pages

### ISSUE THREAD

**Issue by Vogtinator** [openSUSE/build-check-statistics#4]
Opening e.g. https://rpmlint.opensuse.org/72082225 does not work in web browsers.
This is because the server specifies that the content is gzip compressed, but it serves plaintext anyway:

```
~> openssl s_client -connect rpmlint.opensuse.org:443
CONNECTED(00000003)
...
GET /72082225 HTTP/1.1
Host: rpmlint.opensuse.org
Accept-Encoding: gzip

HTTP/1.1 200 OK
date: Tue, 26 Apr 2022 07:21:08 GMT
vary: Accept-Encoding
content-encoding: gzip
content-length: 2879
content-type: text/html;charset=UTF-8
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
referrer-policy: no-referrer-when-downgrade
strict-transport-security: max-age=15768000

<!DOCTYPE html>
<html>
...
</html>
closed
```

**Comment by kraih** [comment]
Interesting, i've been looking for a case like this to track down an upstream bug in Mojolicious. Been aware it existed because we've been getting reports every now and then, but no case that could be replicated so far.

**Comment by kraih** [comment]
Should all work again. And it wasn't an upstream bug at all, just a case of a double rendering bug becoming an issue because only one version was above the compression threshold.

**Comment by Vogtinator** [comment]
Confirmed, thanks!
